import Link from "next/link";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { getPaymentStatus } from "@/lib/payment-service";
import { requirePermission } from "@/lib/session";

type Props={searchParams:Promise<{query?:string;hostel?:string;status?:string;type?:string;from?:string;to?:string;month?:string;summary?:string}>};
const money=(value:number)=>`${value.toFixed(2)} zł`;
const statusLabel=(s:string)=>s==="paid"?"Оплачено":s==="overdue"?"Прострочено":"Очікує";
const statusClass=(s:string)=>s==="paid"?"bg-green-100 text-green-700":s==="overdue"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700";
const typeLabel=(s:string)=>s==="DEPOSIT"?"Застава":s==="OTHER"?"Інше":"Оренда";
const methodLabel=(s:string)=>({CASH:"Готівка",BLIK:"BLIK",BANK_TRANSFER:"Переказ",CARD:"Картка",COMPANY:"Фірма",OTHER:"Інше"} as Record<string,string>)[s]||"—";
const toId=(v?:string)=>{const n=Number(v);return Number.isInteger(n)&&n>0?n:undefined};

export default async function PaymentsPage({searchParams}:Props){
 const p=await searchParams; const now=new Date(); const selected=/^\d{4}-\d{2}$/.test(p.month||"")?p.month!:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`; const [year,month]=selected.split("-").map(Number); const monthStart=new Date(year,month-1,1); const monthEnd=new Date(year,month,1); const {workspace}=await requirePermission("PAYMENTS_VIEW"); const hostelId=toId(p.hostel);
 const filters:Prisma.PaymentWhereInput[]=[{resident:{workspaceId:workspace.id}}]; if(p.query?.trim())filters.push({resident:{OR:[{firstName:{contains:p.query.trim(),mode:"insensitive"}},{lastName:{contains:p.query.trim(),mode:"insensitive"}}]}}); if(hostelId)filters.push({resident:{bed:{is:{room:{hostelId}}}}}); if(p.status==="paid")filters.push({paid:true}); if(p.status==="pending")filters.push({paid:false,dueDate:{gte:now}}); if(p.status==="overdue")filters.push({paid:false,dueDate:{lt:now}}); if(["RENT","DEPOSIT","OTHER"].includes(p.type||""))filters.push({type:p.type as "RENT"|"DEPOSIT"|"OTHER"}); if(p.from||p.to)filters.push({dueDate:{...(p.from?{gte:new Date(p.from)}:{}),...(p.to?{lte:new Date(`${p.to}T23:59:59`)}:{})}});
 const [payments,hostels,residents,deposits]=await Promise.all([
  prisma.payment.findMany({where:{AND:filters},include:{resident:{include:{bed:{include:{room:{include:{hostel:true}}}}}}},orderBy:{dueDate:"desc"}}),
  prisma.hostel.findMany({where:{workspaceId:workspace.id},orderBy:{name:"asc"}}),
  prisma.resident.findMany({where:{workspaceId:workspace.id,isActive:true,monthlyRent:{not:null}},include:{bed:{include:{room:{include:{hostel:true}}}},payments:{where:{type:"RENT",paid:true,paidAt:{gte:monthStart,lt:monthEnd}},select:{amount:true}}},orderBy:{lastName:"asc"}}),
  prisma.payment.aggregate({_sum:{amount:true},where:{resident:{workspaceId:workspace.id},type:"DEPOSIT",paid:true}})
 ]);
 const obligations=residents.map(r=>{const maxDay=new Date(year,month,0).getDate();const due=new Date(year,month-1,Math.min(r.paymentDueDay||r.checkIn.getDate(),maxDay),23,59,59);const paid=r.payments.reduce((s,x)=>s+Number(x.amount),0);const expected=Number(r.monthlyRent||0);const remaining=Math.max(0,expected-paid);const state=remaining===0?"paid":due<now?"overdue":"pending";return{r,due,paid,expected,remaining,state};});
 const received=obligations.reduce((s,x)=>s+x.paid,0), expected=obligations.filter(x=>x.state==="pending").reduce((s,x)=>s+x.remaining,0), overdue=obligations.filter(x=>x.state==="overdue").reduce((s,x)=>s+x.remaining,0); const summaryItems=obligations.filter(x=>p.summary?x.state===p.summary:false);
 const monthValue=(offset:number)=>{const d=new Date(year,month-1+offset,1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`};
 return <main className="p-4 sm:p-6 lg:p-8"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-4xl font-bold">Платежі</h1><p className="mt-2 text-slate-500">Контроль оренди за місяцями</p></div><Link href="/payments/new" className="primary-action rounded-xl px-5 py-3 font-medium">+ Додати платіж</Link></header>
 <div className="month-switch mt-6"><Link href={`/payments?month=${monthValue(-1)}`}>←</Link><strong>{monthStart.toLocaleDateString("uk-UA",{month:"long",year:"numeric"})}</strong><Link href={`/payments?month=${monthValue(1)}`}>→</Link></div>
 <div className="payment-summary mt-4"><Link href={`/payments?month=${selected}&summary=paid`}><span>Отримано цього місяця</span><b>{money(received)}</b></Link><Link href={`/payments?month=${selected}&summary=pending`}><span>Очікується до кінця місяця</span><b>{money(expected)}</b></Link><Link href={`/payments?month=${selected}&summary=overdue`} className="danger"><span>Прострочено</span><b>{money(overdue)}</b></Link></div>
 <details className="deposit-summary mt-3"><summary>Застави на зберіганні · {money(Number(deposits._sum.amount||0))}</summary><p>Застави обліковуються окремо та не входять у дохід від оренди.</p></details>
 {p.summary&&<section className="mt-5 rounded-2xl border bg-white p-4"><h2 className="font-bold">{statusLabel(p.summary)} · {summaryItems.length} мешканців</h2><div className="mt-3 divide-y">{summaryItems.map(({r,due,paid,remaining})=><div key={r.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><Link href={`/residents/${r.id}`} className="font-semibold">{r.lastName} {r.firstName}</Link><p className="text-sm text-slate-500">{r.bed?.room.hostel.name||"—"} · {r.bed?.room.name||"—"} · {r.phone||"без телефона"}</p></div><div className="text-right"><b>{p.summary==="paid"?money(paid):money(remaining)}</b><p className="text-sm text-slate-500">до {due.toLocaleDateString("uk-UA")}</p></div></div>)}</div>{summaryItems.length===0&&<p className="mt-3 text-slate-500">Список порожній.</p>}</section>}
 <form className="payment-filters mt-6 rounded-2xl border bg-white p-4"><label className="wide">Пошук<input name="query" defaultValue={p.query} placeholder="Ім’я або прізвище"/></label><label>Хостел<select name="hostel" defaultValue={hostelId||""}><option value="">Усі</option>{hostels.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label>Тип<select name="type" defaultValue={p.type||""}><option value="">Усі</option><option value="RENT">Оренда</option><option value="DEPOSIT">Застава</option><option value="OTHER">Інше</option></select></label><label>Статус<select name="status" defaultValue={p.status||""}><option value="">Усі</option><option value="paid">Оплачено</option><option value="pending">Очікує</option><option value="overdue">Прострочено</option></select></label><label>Період від<input type="date" name="from" defaultValue={p.from}/></label><label>Період до<input type="date" name="to" defaultValue={p.to}/></label><div className="filter-actions"><button>Застосувати</button><Link href="/payments">Очистити</Link></div></form>
 <div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-left text-sm"><thead><tr>{["Мешканець","Хостел","Кімната","Сума","Тип","Планова дата","Оплачено","Статус"].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody className="divide-y">{payments.map(x=>{const s=getPaymentStatus(x,now);return <tr key={x.id}><td className="px-5 py-4"><Link href={`/payments/${x.id}`}>{x.resident.firstName} {x.resident.lastName}</Link></td><td className="px-5 py-4">{x.resident.bed?.room.hostel.name||"—"}</td><td className="px-5 py-4">{x.resident.bed?.room.name||"—"}</td><td className="px-5 py-4">{money(Number(x.amount))}</td><td className="px-5 py-4">{typeLabel(x.type)}<small className="block">{methodLabel(x.method)}</small></td><td className="px-5 py-4">{x.dueDate.toLocaleDateString("uk-UA")}</td><td className="px-5 py-4">{x.paidAt?.toLocaleDateString("uk-UA")||"—"}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 ${statusClass(s)}`}>{statusLabel(s)}</span></td></tr>})}</tbody></table>{payments.length===0&&<p className="p-8 text-center text-slate-500">Платежів не знайдено.</p>}</div></main>;
}
